export const wikiNavOrder = [
  '/wiki',
  '/wiki/about/why-luckperms',
  '/wiki/about/credits',
  '/wiki/about/locale',
  '/wiki/about/placeholders',
  '/wiki/about/external-connections',
  '/wiki/install',
  '/wiki/install/network',
  '/wiki/install/hytale',
  '/wiki/getting-started',
  '/wiki/storage',
  '/wiki/configuration',
  '/wiki/faq',
  '/wiki/commands',
  '/wiki/commands/general',
  '/wiki/commands/user',
  '/wiki/commands/group',
  '/wiki/commands/permission',
  '/wiki/commands/parent',
  '/wiki/commands/meta',
  '/wiki/commands/track',
  '/wiki/commands/log',
  '/wiki/commands/permissions',
  '/wiki/features/web-editor',
  '/wiki/features/web-editor/technical',
  '/wiki/features/context',
  '/wiki/features/weight',
  '/wiki/features/prefixes-suffixes-meta',
  '/wiki/features/verbose',
  '/wiki/features/tracks',
  '/wiki/features/default-groups',
  '/wiki/guides/syncing',
  '/wiki/guides/storage-errors',
  '/wiki/guides/migration',
  '/wiki/guides/switching-storage',
  '/wiki/guides/bulk-editing',
  '/wiki/guides/prefix-stacking',
  '/wiki/guides/extensions',
  '/wiki/guides/argument-permissions',
  '/wiki/developers/api',
  '/wiki/developers/api-usage',
  '/wiki/developers/standalone-rest',
  '/wiki/developers/contributing',
  '/wiki/reference/upgrade-v4-v5',
  '/wiki/reference/migrating-gm-pex',
  '/wiki/reference/permission-calculation',
  '/wiki/reference/self-hosting'
]

export const wikiSections = [
  { title: 'About', paths: [
    '/wiki/about/why-luckperms',
    '/wiki/about/credits',
    '/wiki/about/locale',
    '/wiki/about/placeholders',
    '/wiki/about/external-connections'
  ] },
  { title: 'Install', paths: ['/wiki/install', '/wiki/install/network', '/wiki/install/hytale'] },
  { title: 'Getting started', paths: ['/wiki/getting-started', '/wiki/storage', '/wiki/configuration', '/wiki/faq'] },
  { title: 'Commands', paths: [
    '/wiki/commands',
    '/wiki/commands/general',
    '/wiki/commands/user',
    '/wiki/commands/group',
    '/wiki/commands/permission',
    '/wiki/commands/parent',
    '/wiki/commands/meta',
    '/wiki/commands/track',
    '/wiki/commands/log',
    '/wiki/commands/permissions'
  ] },
  { title: 'Features', paths: [
    '/wiki/features/web-editor',
    '/wiki/features/web-editor/technical',
    '/wiki/features/context',
    '/wiki/features/weight',
    '/wiki/features/prefixes-suffixes-meta',
    '/wiki/features/verbose',
    '/wiki/features/tracks',
    '/wiki/features/default-groups'
  ] },
  { title: 'Guides', paths: [
    '/wiki/guides/syncing',
    '/wiki/guides/storage-errors',
    '/wiki/guides/migration',
    '/wiki/guides/switching-storage',
    '/wiki/guides/bulk-editing',
    '/wiki/guides/prefix-stacking',
    '/wiki/guides/extensions',
    '/wiki/guides/argument-permissions'
  ] },
  { title: 'Developers', paths: [
    '/wiki/developers/api',
    '/wiki/developers/api-usage',
    '/wiki/developers/standalone-rest',
    '/wiki/developers/contributing'
  ] },
  { title: 'Reference', paths: [
    '/wiki/reference/upgrade-v4-v5',
    '/wiki/reference/migrating-gm-pex',
    '/wiki/reference/permission-calculation',
    '/wiki/reference/self-hosting'
  ] }
]
