# Hybrid: prerendered marketing/wiki, SPA only for tools
server {
	listen 80 default_server;

	gzip on;
	gzip_min_length 1000;
	gzip_types text/plain text/xml application/javascript text/css;

	root /usr/share/nginx/html;

	location /editor {
		try_files $uri $uri/ /editor/index.html;
	}

	location /verbose {
		try_files $uri $uri/ /verbose/index.html;
	}

	location /treeview {
		try_files $uri $uri/ /treeview/index.html;
	}

	location / {
		try_files $uri $uri/index.html =404;
	}
}
